services:
    liker_oauth2_proxy:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        ports:
            - "4180:4180"
        volumes:
            - ./:/workspace
        networks:
            - liker_external_network
            - liker_oauth2_proxy_internal_network
        dns:
            - 8.8.8.8
        environment:
            - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
            - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
            - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
            - OAUTH2_PROXY_REVERSE_PROXY=${OAUTH2_PROXY_REVERSE_PROXY}
            - OAUTH2_PROXY_COOKIE_SECURE=${OAUTH2_PROXY_COOKIE_SECURE}
            - OAUTH2_PROXY_SET_AUTHORIZATION_HEADER=${OAUTH2_PROXY_SET_AUTHORIZATION_HEADER}
            - OAUTH2_PROXY_SET_XAUTHREQUEST=${OAUTH2_PROXY_SET_XAUTHREQUEST}
            - OAUTH2_PROXY_EMAIL_DOMAINS=${OAUTH2_PROXY_EMAIL_DOMAINS}
            - OAUTH2_PROXY_HTTP_ADDRESS=${OAUTH2_PROXY_HTTP_ADDRESS}
            - OAUTH2_PROXY_REDIRECT_URL=${OAUTH2_PROXY_REDIRECT_URL}
            - OAUTH2_PROXY_SESSION_STORE_TYPE=${OAUTH2_PROXY_SESSION_STORE_TYPE}
            - OAUTH2_PROXY_COOKIE_SAMESITE=${OAUTH2_PROXY_COOKIE_SAMESITE}
            - OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST=${OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST}
            - OAUTH2_PROXY_COOKIE_CSRF_EXPIRE=${OAUTH2_PROXY_COOKIE_CSRF_EXPIRE}
            - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=${OAUTH2_PROXY_SKIP_PROVIDER_BUTTON}
            - OAUTH2_PROXY_PASS_USER_HEADERS=${OAUTH2_PROXY_PASS_USER_HEADERS}
            - OAUTH2_PROXY_COOKIE_DOMAINS=${OAUTH2_PROXY_COOKIE_DOMAINS}
            - OAUTH2_PROXY_WHITELIST_DOMAINS=${OAUTH2_PROXY_WHITELIST_DOMAINS}
networks:
    liker_external_network:
        external: true
        name: "liker"
    liker_oauth2_proxy_internal_network:
        external: false
        name: "liker_oauth2_proxy_internal_network"
